behaviors:
  DoggyBehavior:
    trainer_type: ppo
    keep_checkpoints: 100
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 15000
    checkpoint_interval: 50000
    threaded: true
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    reward_signals:
      extrinsic:
        strength: 1.0 
        gamma: 0.99

environment_parameters:
  cube_distance:
    curriculum:
      - name: Lesson0 # Very easy - find your feet
        completion_criteria:
          measure: reward
          behavior: DoggyBehavior
          threshold: 15.0
          min_lesson_length: 100
          signal_smoothing: true
        value: 2.5
      - name: Lesson1 # Small step forward
        completion_criteria:
          measure: reward
          behavior: DoggyBehavior
          threshold: 25.0
          min_lesson_length: 100
          signal_smoothing: true
        value: 3.5
      - name: Lesson2 # Intermediate distance
        completion_criteria:
          measure: reward
          behavior: DoggyBehavior
          threshold: 30.0
          min_lesson_length: 100
          signal_smoothing: true
        value: 4.5
      - name: Lesson3 # The current challenge
        completion_criteria:
          measure: reward
          behavior: DoggyBehavior
          threshold: 35.0
          min_lesson_length: 100
          signal_smoothing: true
        value: 5.5
      - name: Lesson4 # Final Boss
        value: 10.0